### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by Chlience** [Noisyfox/sysproxy#4]
因为想要配置系统代理，而又不想重复造轮子，看到您的实现非常棒（内置在ss中），想要了解一下

**Comment by Noisyfox** [comment]
我加了个 readme，希望足够清楚啦~

**Comment by Chlience** [comment]
现在应用已经成功整合，再次感谢您的支持qwq
地址：[V2RayC](https://github.com/Chlience/V2RayC)
