### ISSUE TITLE
use SOCK5 instead?

### ISSUE THREAD

**Issue by malikshi** [Noisyfox/sysproxy#5]
how to use socks5 ?

**Comment by UzminTid** [comment]
windows dose NOT have native support of Socks5 (only have Socks4)
So you must convert it to https proxy using privoxy or anything like that

**Comment by WillDawnlll** [comment]
> 
> 
> windows dose NOT have native support of Socks5 (only have Socks4)
> So you must convert it to https proxy using privoxy or anything like that
https://windowsreport.com/windows-10-socks5-proxy-settings/
Is the way here socks5?
(use  internet connect windows to setup)
